<?php

namespace Documentor\Parsers;

/**
 * Test class for ConstantParser.
 * Generated by PHPUnit on 2012-11-21 at 17:28:45.
 */
class ConstantParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConstantParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConstantParser(__DIR__ .'/../Resources/TestClass.php');
    }

    /**
     */
    public function testParse() {
        $res = $this->object->parse();
        $this->assertTrue(is_array($res));
        $this->assertEquals(4, count($res));
        
        $joebar = $res[3];
        $this->assertEquals("JOE_BAR", $joebar['name']);
        $this->assertEquals("'test'", $joebar['value']);
        $this->assertEquals(82, $joebar['startLine']);
        $this->assertEquals(82, $joebar['endLine']);
    }
}
