<?php

namespace Documentor\Parsers;


/**
 * Test class for FunctionParser.
 * Generated by PHPUnit on 2012-11-21 at 17:40:51.
 */
class FunctionParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FunctionParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FunctionParser(__DIR__ .'/../Resources/TestClass.php');
    }
    /**
     */
    public function testParse() {
        $res = $this->object->parse();
        $this->assertTrue(is_array($res));
        $this->assertEquals(2, count($res));
        
        $this->assertEquals("testFunction", $res[0]['name']);
        $this->assertEquals("joeBarTeam", $res[1]['name']);
    }
}