<?php

namespace Documentor\Parsers;


/**
 * Test class for ImportsParser.
 * Generated by PHPUnit on 2012-10-20 at 16:39:47.
 */
class ImportsParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ImportsParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ImportsParser(__DIR__ .'/../Resources/TestClass.php');
    }

    /**
     */
    public function testParse() {
        $res = $this->object->parse();
        $this->assertTrue(is_array($res));
        $this->assertEquals(3, count($res));
    }
    
    public function testResults()
    {
       $res = $this->object->parse();
       
       $this->assertEquals('\RuntimeException', $res[0]['import']);
       $this->assertEquals('\stdClass', $res[1]['import']);
       $this->assertNull($res[1]['alias']);
       $this->assertEquals('\Exception', $res[2]['import']);
       $this->assertEquals('BaseException', $res[2]['alias']);
    }
}