<?php

namespace Documentor\Parsers;

require_once dirname(__FILE__) . '/../../Parsers/MethodParser.php';

/**
 * Test class for MethodParser.
 * Generated by PHPUnit on 2012-11-21 at 17:37:41.
 */
class MethodParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MethodParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MethodParser(__DIR__ .'/../Resources/TestClass.php');
    }

    /**
     */
    public function testParse()
    {
        $res = $this->object->parse();
        $this->assertTrue(is_array($res));
        $this->assertEquals(4, count($res));
        
        $this->assertEquals("test", $res[3]['name']);
        $this->assertEquals("factory", $res[2]['name']);
        $this->assertEquals("testMethod", $res[1]['name']);
        $this->assertEquals("__construct", $res[0]['name']);
    }

}