### <?php echo $function->getShortName(); ?>


``` php

<?php echo $function->getSignatureString(); ?>

```

<?php if ($function->getDocComment() !== null): ?>
<?php echo strip_tags($function->getDocComment()->getComment()); ?>

<?php endif; ?>
<?php
    $params = $function->getParameters();
    $doc = $function->getDocComment();

    $paramsTags = (isset($doc) ? $doc->getTags('param') : array());
    $returnTag = (isset($doc) ? $doc->getFirstTag('return') : null);
?>
<?php if(count($params)): ?>
##### Parameters

<?php foreach($params as $parameter): ?>
* $**<?php echo $parameter->getName() ?>** <?php if($parameter->isOptional()): ?>*(optional)*<?php endif; ?>

  <?php echo (isset($paramsTags[$parameter->getPosition()]) ? $paramsTags[$parameter->getPosition()]->getDescription() : "*no description*"); ?>

<?php endforeach; ?>
<?php endif; ?>

##### Return type

```<?php echo (isset($returnTag) ? $returnTag->getText() : "mixed"); ?>```

---

