<?php
 $classes = $resource->getProject()->getNamespaceClasses($resource->namespaceName);
 $nsFuncs = $resource->getProject()->getNamespaceFunctions($resource->namespaceName);
 $nsInterfaces = array();
 $nsClasses = array();
 $nses      = $resource->getProject()->getNamespaceNamespaces($resource->namespaceName);

 foreach($classes as $class) {
     if($class->isInterface()) {
         $nsInterfaces[$class->getShortName()] = $class;
     } else {
         $nsClasses[$class->getShortName()] = $class;
     }
 }

?>
# Namespace: [<?php echo $resource->namespaceName; ?>](<?php echo $resource->url($resource->namespaceName, 'namespace', $resource->namespaceName); ?>.md)

<?php if(count($classes)): ?>
## Classes

<?php foreach ($nsClasses as $class): ?>
* [<?php echo $class->getShortName(); ?>](<?php echo $resource->url($class->getName(), 'class', $resource->namespaceName); ?>.md)
<?php endforeach; ?>

<?php endif; ?>
<?php if(count($nsInterfaces)): ?>
## Interfaces

<?php foreach ($nsInterfaces as $class): ?>
* [<?php echo $class->getShortName(); ?>](<?php echo $resource->url($class->getName(), 'class', $resource->namespaceName); ?>.md)
<?php endforeach; ?>

<?php endif; ?>
<?php if (count($nsFuncs)): ?>
## Functions

<?php foreach ($nsFuncs as $function): ?>
* [<?php echo $function->getShortName(); ?>](#<?php echo strtolower($function->getShortName()); ?>)
<?php endforeach; ?>

---

<?php

foreach ($nsFuncs as $function) {
    include __DIR__ .'/function.phtml';
}
?>
<?php endif; ?>

<?php if (count($nses)): ?>
## Others Namespaces

<?php foreach ($nses as $namespace): ?>
* [<?php echo $namespace; ?>](<?php echo $resource->url($namespace, 'namespace', $resource->namespaceName); ?>.md)
<?php endforeach; ?>
<?php endif; ?>
