<?php
 $classes = $this->getProject()->getNamespaceClasses($this->namespaceName);
 $nsFuncs = $this->getProject()->getNamespaceFunctions($this->namespaceName);
 $nsInterfaces = array();
 $nsClasses = array();

 foreach($classes as $class) {
     if($class->isInterface()) {
         $nsInterfaces[$class->getShortName()] = $class;
     } else {
         $nsClasses[$class->getShortName()] = $class;
     }
 }

?>
# Namespace: [<?php echo $this->namespaceName; ?>](<?php echo $this->url($this->namespaceName, 'namespace', $this->namespaceName); ?>.md)

<?php if(count($classes)): ?>
## Classes

<?php foreach ($nsClasses as $class): ?>
* [<?php echo $class->getShortName(); ?>](<?php echo $this->url($class->getName(), 'class', $this->namespaceName); ?>.md)
<?php endforeach; ?>

<?php endif; ?>
<?php if(count($nsInterfaces)): ?>
## Interfaces

<?php foreach ($nsInterfaces as $class): ?>
* *<?php echo $class->getShortName(); ?>*
<?php endforeach; ?>

<?php endif; ?>
<?php if (count($nsFuncs)): ?>
## Functions

<?php foreach ($nsFuncs as $function): ?>
* [<?php echo $function->getShortName(); ?>](#<?php echo strtolower($function->getShortName()); ?>)
<?php endforeach; ?>

---

<?php 

foreach ($nsFuncs as $function) {
    include __DIR__ .'/function.phtml';
}
?>
<?php endif; ?>