### $<?php echo $property->getName(); ?>

```
<?php echo $property->getVisibility(); ?> <?php echo ($property->isStatic() ? 'static ' : '') ?>$<?php echo $property->getName(); ?>

```

<?php if ($property->getDocComment() !== null): ?>
<?php echo strip_tags($property->getDocComment()->getComment()); ?>

<?php endif; ?>

<?php
    $doc = $property->getDocComment();

    $returnTag = (isset($doc) ? $doc->getFirstTag('var') : null);
?>

<?php if(isset($returnTag)): ?>
##### Type

<?php echo typeLink($this, $returnTag, (isset($reflector) ? $reflector->getName() : $this->namespaceName)); ?> 

<?php endif; ?>

---

